import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider extends ChangeNotifier {
  Locale _currentLocale = const Locale('en');
  bool _isFirstTime = true;

  Locale get currentLocale => _currentLocale;
  bool get isFirstTime => _isFirstTime;

  LanguageProvider() {
    _loadFromPrefs();
  }

  Future<void> _loadFromPrefs() async {
    final prefs = await SharedPreferences.getInstance();
    final langCode = prefs.getString('language_code') ?? 'en';
    _isFirstTime = prefs.getBool('is_first_time') ?? true;
    _currentLocale = Locale(langCode);
    notifyListeners();
  }

  Future<void> setLanguage(String langCode) async {
    _currentLocale = Locale(langCode);
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('language_code', langCode);
    notifyListeners();
  }

  Future<void> setFirstTimeCompleted() async {
    _isFirstTime = false;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool('is_first_time', false);
    notifyListeners();
  }

  String translate(String key) {
    return _translations[_currentLocale.languageCode]?[key] ?? key;
  }

  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'select_language': 'Select Language',
      'welcome': 'Welcome to PharmaCo',
      'continue': 'Continue',
      'profile': 'Profile',
      'change_language': 'Change Language',
      'logout': 'Logout',
      'navigate_pharmacy': 'Navigate to Pharmacy',
      'navigate_customer': 'Navigate to Customer',
      'at_pharmacy': 'At Pharmacy',
      'heading_pharmacy': 'Heading to Pharmacy',
      'heading_customer': 'Heading to Customer',
      'call': 'CALL',
      'arrived': 'I HAVE ARRIVED',
      'picked_up': 'PICKED UP',
      're_direct': 'RE-DIRECT TO MAPS',
      'updating': 'Updating...',
      'navigating_to': 'Navigating to',
      'login': 'Login',
      'email': 'Email',
      'password': 'Password',
      'orders': 'Orders',
      'earnings': 'Earnings',
      'settings': 'Settings',
      'home': 'Home',
      'welcome_partner': 'Welcome, Partner',
      'sign_in_to_continue': 'Sign in to your account',
      'email_address': 'Email Address',
      'forgot_password': 'Forgot Password?',
      'dont_have_account': "Don't have an account?",
      'sign_up': 'Sign Up',
      'invalid_email': 'Please enter a valid email',
      'enter_password': 'Please enter your password',
      'signing_in': 'SIGNING IN...',
      'sign_in': 'SIGN IN',
      'dashboard': 'Dashboard',
      'my_earnings': 'My Earnings',
      'profile_account': 'Profile & Account',
      'exit_app': 'Exit App',
      'exit_confirm': 'Are you sure you want to exit the app?',
      'cancel': 'CANCEL',
      'exit': 'EXIT',
      'available': 'Available',
      'my_orders': 'My Orders',
      'real_time_updates': 'Real-time updates active',
      'no_orders_nearby': 'No orders nearby',
      'notify_new_orders': "We'll notify you when new orders appear in your area.",
      'urgent': 'URGENT',
      'km_away': 'km away',
      'nearby': 'Nearby',
      'no_active_orders': 'No Active Orders',
      'no_past_orders': 'No Past Orders',
      'go_online_to_receive': 'Go online on the dashboard to start receiving orders.',
      'past_orders_appear_here': 'Your completed or cancelled orders will appear here.',
      'order_from': 'Order from',
      'navigate_to_delivery': 'NAVIGATE TO DELIVERY',
      'order_statuses': 'Order Statuses',
      'pending_status_desc': 'You have accepted this order and need to complete the delivery.',
      'completed_status_desc': 'You have successfully completed this delivery.',
      'cancelled_status_desc': 'This order was cancelled by the customer or the system.',
      'order_payout': 'Order Payout',
      'transfer': 'Transfer',
      'available_balance': 'Available Balance',
      'next_settlement': 'Next settlement in',
      'upi_transfer': 'UPI TRANSFER',
      'bank_payout': 'BANK PAYOUT',
      'recent_transactions': 'Recent Transactions',
      'filters': 'Filters',
      'no_transactions': 'No transactions yet',
      'today': 'Today',
      'lifetime': 'Lifetime',
      'retry': 'Retry',
      'online': 'Online',
      'offline': 'Offline',
      'waiting_for_orders': 'Waiting for orders...',
      'go_online_to_earn': 'Go online to start earning',
      'active_delivery': 'ACTIVE DELIVERY',
      'tap_to_view_details': 'Tap to view details & navigate',
      'todays_earnings': 'Today\'s Earnings',
      'completed': 'Completed',
      'recent_activity': 'Recent Activity',
      'view_all': 'View All',
      'no_recent_activity': 'No recent activity to show',
      'complete_orders_to_see': 'Complete orders to see them here',
      'verification_required': 'Verification Required',
      'complete_verification_desc': 'Complete verification to start delivering.',
      'verification_pending': 'Verification Pending',
      'complete_verification_long_desc': 'Complete your document verification to start delivering and earning with PharmaCo.',
      'complete_verification': 'COMPLETE VERIFICATION',
      'cannot_go_offline_active_order': 'Cannot go offline while you have an active delivery.',
      'complete_profile_to_go_online': 'Please complete your profile to go online.',
      'available_orders': 'Available orders',
      'estimated_payout': 'Estimated Payout',
      'order_accepted': 'Order Accepted',
      'accept': 'ACCEPT',
      'past_history': 'Past History',
      'no_orders_found': 'No orders found',
      'my_orders_empty_desc': 'Your assigned and past orders will appear here',
      'could_not_open_maps': 'Could not open maps.',
      'delivery_loc_not_available': 'Delivery location not available.',
      'pending': 'Pending',
      'failed_to_load_profile': 'Failed to load profile',
      'delivered': 'DELIVERED',
      'ready': 'READY',
      'preparing': 'PREPARING',
      'active_orders': 'Active Orders',
      'confirm_pickup': 'Confirm Pickup',
      'confirm_delivery': 'Confirm Delivery',
    },
    'hi': {
      'select_language': 'भाषा चुनें',
      'welcome': 'PharmaCo में आपका स्वागत है',
      'continue': 'जारी रखें',
      'profile': 'प्रोफ़ाइल',
      'change_language': 'भाषा बदलें',
      'logout': 'लॉग आउट',
      'navigate_pharmacy': 'फार्मेसी पर जाएं',
      'navigate_customer': 'ग्राहक पर जाएं',
      'at_pharmacy': 'फार्मेसी पर',
      'heading_pharmacy': 'फार्मेसी की ओर',
      'heading_customer': 'ग्राहक की ओर',
      'call': 'कॉल करें',
      'arrived': 'मैं पहुँच गया हूँ',
      'picked_up': 'पिकअप किया',
      're_direct': 'मैप्स पर वापस जाएं',
      'updating': 'अपडेट हो रहा है...',
      'navigating_to': 'जा रहे हैं',
      'login': 'लॉगिन',
      'email': 'ईमेल',
      'password': 'पासवर्ड',
      'orders': 'ऑर्डर',
      'earnings': 'कमाई',
      'settings': 'सेटिंग्स',
      'home': 'होम',
      'welcome_partner': 'स्वागत है, पार्टनर',
      'sign_in_to_continue': 'अपने खाते में साइन इन करें',
      'email_address': 'ईमेल पता',
      'forgot_password': 'पासवर्ड भूल गए?',
      'dont_have_account': 'खाता नहीं है?',
      'sign_up': 'साइन अप करें',
      'invalid_email': 'कृपया एक वैध ईमेल दर्ज करें',
      'enter_password': 'कृपया अपना पासवर्ड दर्ज करें',
      'signing_in': 'साइन इन हो रहा है...',
      'sign_in': 'साइन इन करें',
      'dashboard': 'डैशबोर्ड',
      'my_earnings': 'मेरी कमाई',
      'profile_account': 'प्रोफ़ाइल और खाता',
      'exit_app': 'ऐप से बाहर निकलें',
      'exit_confirm': 'क्या आप वाकई ऐप से बाहर निकलना चाहते हैं?',
      'cancel': 'रद्द करें',
      'exit': 'बाहर निकलें',
      'available': 'उपलब्ध',
      'my_orders': 'मेरे ऑर्डर',
      'real_time_updates': 'रीयल-टाइम अपडेट सक्रिय',
      'no_orders_nearby': 'आस-पास कोई ऑर्डर नहीं है',
      'notify_new_orders': 'जब आपके क्षेत्र में नए ऑर्डर आएंगे तो हम आपको सूचित करेंगे।',
      'urgent': 'जरूरी',
      'km_away': 'किमी दूर',
      'nearby': 'आस-पास',
      'no_active_orders': 'कोई सक्रिय ऑर्डर नहीं',
      'no_past_orders': 'कोई पुराने ऑर्डर नहीं',
      'go_online_to_receive': 'ऑर्डर प्राप्त करना शुरू करने के लिए डैशबोर्ड पर ऑनलाइन जाएं।',
      'past_orders_appear_here': 'आपके पूरे किए गए या रद्द किए गए ऑर्डर यहां दिखाई देंगे।',
      'order_from': 'ऑर्डर की ओर से',
      'navigate_to_delivery': 'डिलीवरी के लिए नेविगेट करें',
      'order_statuses': 'ऑर्डर की स्थिति',
      'pending_status_desc': 'आपने इस ऑर्डर को स्वीकार कर लिया है और डिलीवरी पूरी करनी होगी।',
      'completed_status_desc': 'आपने यह डिलीवरी सफलतापूर्वक पूरी कर ली है।',
      'cancelled_status_desc': 'यह ऑर्डर ग्राहक या सिस्टम द्वारा रद्द कर दिया गया था।',
      'order_payout': 'ऑर्डर भुगतान',
      'transfer': 'ट्रांसफर',
      'available_balance': 'उपलब्ध शेष राशि',
      'next_settlement': 'अगला सेटलमेंट',
      'upi_transfer': 'UPI ट्रांसफर',
      'bank_payout': 'बैंक भुगतान',
      'recent_transactions': 'हाल के लेनदेन',
      'filters': 'फ़िल्टर',
      'no_transactions': 'अभी तक कोई लेनदेन नहीं हुआ',
      'today': 'आज',
      'lifetime': 'जीवनकाल',
      'retry': 'पुनः प्रयास करें',
      'online': 'ऑनलाइन',
      'offline': 'ऑफलाइन',
      'waiting_for_orders': 'ऑर्डर की प्रतीक्षा की जा रही है...',
      'go_online_to_earn': 'कमाई शुरू करने के लिए ऑनलाइन जाएं',
      'active_delivery': 'सक्रिय डिलीवरी',
      'tap_to_view_details': 'विवरण देखने और नेविगेट करने के लिए टैप करें',
      'todays_earnings': 'आज की कमाई',
      'completed': 'पूरा हुआ',
      'recent_activity': 'हाल की गतिविधि',
      'view_all': 'सभी देखें',
      'no_recent_activity': 'दिखाने के लिए कोई हाल की गतिविधि नहीं',
      'complete_orders_to_see': 'उन्हें यहां देखने के लिए ऑर्डर पूरे करें',
      'verification_required': 'सत्यापन आवश्यक',
      'complete_verification_desc': 'डिलीवरी शुरू करने के लिए सत्यापन पूरा करें।',
      'verification_pending': 'सत्यापन लंबित',
      'complete_verification_long_desc': 'PharmaCo के साथ डिलीवरी और कमाई शुरू करने के लिए अपना दस्तावेज़ सत्यापन पूरा करें।',
      'complete_verification': 'सत्यापन पूरा करें',
      'cannot_go_offline_active_order': 'जब आपके पास सक्रिय डिलीवरी हो तो आप ऑफलाइन नहीं जा सकते।',
      'complete_profile_to_go_online': 'ऑनलाइन जाने के लिए कृपया अपना प्रोफ़ाइल पूरा करें।',
      'available_orders': 'उपलब्ध ऑर्डर',
      'estimated_payout': 'अनुमानित भुगतान',
      'order_accepted': 'ऑर्डर स्वीकार कर लिया गया!',
      'accept': 'स्वीकार करें',
      'past_history': 'पिछला इतिहास',
      'no_orders_found': 'कोई ऑर्डर नहीं मिला',
      'my_orders_empty_desc': 'आपके सौंपे गए और पुराने ऑर्डर यहां दिखाई देंगे',
      'could_not_open_maps': 'मैप्स नहीं खुल सका।',
      'delivery_loc_not_available': 'डिलीवरी स्थान उपलब्ध नहीं है।',
      'pending': 'लंबित',
      'failed_to_load_profile': 'प्रोफ़ाइल लोड करने में विफल',
      'delivered': 'डिलिवर हो गया',
      'ready': 'तैयार',
      'preparing': 'तैयार हो रहा है',
      'active_orders': 'सक्रिय ऑर्डर',
      'confirm_pickup': 'पिकअप की पुष्टि करें',
      'confirm_delivery': 'डिलीवरी की पुष्टि करें',
    },
    'mr': {
      'select_language': 'भाषा निवडा',
      'welcome': 'PharmaCo मध्ये आपले स्वागत आहे',
      'continue': 'पुढे जा',
      'profile': 'प्रोफाइल',
      'change_language': 'भाषा बदला',
      'logout': 'लॉग आउट',
      'navigate_pharmacy': 'फार्मसीकडे जा',
      'navigate_customer': 'ग्राहकाकडे जा',
      'at_pharmacy': 'फार्मसीवर',
      'heading_pharmacy': 'फार्मसीकडे जात आहे',
      'heading_customer': 'ग्राहकाकडे जात आहे',
      'call': 'कॉल करा',
      'arrived': 'मी पोहोचलो आहे',
      'picked_up': 'पिकअप केले',
      're_direct': 'नकाशावर जा',
      'updating': 'अपडेट होत आहे...',
      'navigating_to': 'येथे जात आहे',
      'login': 'लॉगिन',
      'email': 'ईमेल',
      'password': 'पासवर्ड',
      'orders': 'ऑर्डर',
      'earnings': 'कमाई',
      'settings': 'सेटिंग्ज',
      'home': 'होम',
      'welcome_partner': 'स्वागत आहे, पार्टनर',
      'sign_in_to_continue': 'तुमच्या खात्यात साइन इन करा',
      'email_address': 'ईमेल पत्ता',
      'forgot_password': 'पासवर्ड विसरलात?',
      'dont_have_account': 'खाते नाही?',
      'sign_up': 'साइन अप करा',
      'invalid_email': 'कृपया वैध ईमेल प्रविष्ट करा',
      'enter_password': 'कृपया तुमचा पासवर्ड प्रविष्ट करा',
      'signing_in': 'साइन इन होत आहे...',
      'sign_in': 'साइन इन करा',
      'dashboard': 'डॅशबोर्ड',
      'my_earnings': 'माझी कमाई',
      'profile_account': 'प्रोफाईल आणि खाते',
      'exit_app': 'अॅपमधून बाहेर पडा',
      'exit_confirm': 'तुमची खात्री आहे की तुम्हाला अॅपमधून बाहेर पडायचे आहे?',
      'cancel': 'रद्द करा',
      'exit': 'बाहेर पडा',
      'available': 'उपलब्ध',
      'my_orders': 'माझे ऑर्डर',
      'real_time_updates': 'रिअल-टाइम अपडेट सक्रिय',
      'no_orders_nearby': 'जवळपास कोणतेही ऑर्डर नाहीत',
      'notify_new_orders': 'जेव्हा तुमच्या भागात नवीन ऑर्डर येतील तेव्हा आम्ही तुम्हाला सूचित करू.',
      'urgent': 'तातडीचे',
      'km_away': 'किमी लांब',
      'nearby': 'जवळपास',
      'no_active_orders': 'कोणतेही सक्रिय ऑर्डर नाहीत',
      'no_past_orders': 'कोणतेही जुने ऑर्डर नाहीत',
      'go_online_to_receive': 'ऑर्डर प्राप्त करणे सुरू करण्यासाठी डॅशबोर्डवर ऑनलाइन जा.',
      'past_orders_appear_here': 'तुमचे पूर्ण झालेले किंवा रद्द केलेले ऑर्डर येथे दिसतील.',
      'order_from': 'येथून ऑर्डर',
      'navigate_to_delivery': 'डिलीव्हरीसाठी नेव्हिगेट करा',
      'order_statuses': 'ऑर्डरची स्थिती',
      'pending_status_desc': 'तुम्ही ही ऑर्डर स्वीकारली आहे आणि डिलिव्हरी पूर्ण करणे आवश्यक आहे.',
      'completed_status_desc': 'तुम्ही ही डिलिव्हरी यशस्वीरीत्या पूर्ण केली आहे.',
      'cancelled_status_desc': 'ही ऑर्डर ग्राहक किंवा सिस्टमद्वारे रद्द केली गेली होती.',
      'order_payout': 'ऑर्डर पेआउट',
      'transfer': 'ट्रान्सफर',
      'available_balance': 'उपलब्ध शिल्लक',
      'next_settlement': 'पुढील सेटलमेंट',
      'upi_transfer': 'UPI ट्रान्सफर',
      'bank_payout': 'बँक पेआउट',
      'recent_transactions': 'अलीकडील व्यवहार',
      'filters': 'फिल्टर्स',
      'no_transactions': 'अद्याप कोणतेही व्यवहार नाहीत',
      'today': 'आज',
      'lifetime': 'जीवनकाळ',
      'retry': 'पुन्हा प्रयत्न करा',
      'online': 'ऑनलाइन',
      'offline': 'ऑफलाइन',
      'waiting_for_orders': 'ऑर्डरची प्रतीक्षा करत आहे...',
      'go_online_to_earn': 'कमाई सुरू करण्यासाठी ऑनलाइन जा',
      'active_delivery': 'सक्रिय डिलिव्हरी',
      'tap_to_view_details': 'तपशील पाहण्यासाठी आणि नेव्हिगेट करण्यासाठी टॅप करा',
      'todays_earnings': 'आजची कमाई',
      'completed': 'पूर्ण झाले',
      'recent_activity': 'अलीकडील क्रियाकलाप',
      'view_all': 'सर्व पहा',
      'no_recent_activity': 'दाखवण्यासाठी कोणतीही अलीकडील क्रियाकलाप नाही',
      'complete_orders_to_see': 'ते येथे पाहण्यासाठी ऑर्डर पूर्ण करा',
      'verification_required': 'सत्यापन आवश्यक',
      'complete_verification_desc': 'डिलिव्हरी सुरू करण्यासाठी सत्यापन पूर्ण करा.',
      'verification_pending': 'सत्यापन प्रलंबित',
      'complete_verification_long_desc': 'PharmaCo सह डिलिव्हरी आणि कमाई सुरू करण्यासाठी तुमचे दस्तऐवज सत्यापन पूर्ण करा.',
      'complete_verification': 'सत्यापन पूर्ण करा',
      'cannot_go_offline_active_order': 'तुमच्याकडे सक्रिय डिलिव्हरी असताना तुम्ही offline जाऊ शकत नाही.',
      'complete_profile_to_go_online': 'ऑनलाइन जाण्यासाठी कृपया तुमचे प्रोफाइल पूर्ण करा.',
      'available_orders': 'उपलब्ध ऑर्डर्स',
      'estimated_payout': 'अंदाजित पेआउट',
      'order_accepted': 'ऑर्डर स्वीकारली!',
      'accept': 'स्वीकारा',
      'past_history': 'मागील इतिहास',
      'no_orders_found': 'कोणतेही ऑर्डर सापडले नाहीत',
      'my_orders_empty_desc': 'तुमचे नियुक्त केलेले आणि मागील ऑर्डर्स येथे दिसतील',
      'could_not_open_maps': 'नकाशे उघडता आले नाहीत.',
      'delivery_loc_not_available': 'डिलिव्हरीचे ठिकाण उपलब्ध नाही.',
      'pending': 'प्रलंबित',
      'failed_to_load_profile': 'प्रोफाइल लोड करण्यात अयशस्वी',
      'delivered': 'डिलिव्हर झाले',
      'ready': 'तयार',
      'preparing': 'तयार होत आहे',
      'active_orders': 'सक्रिय ऑर्डर्स',
      'confirm_pickup': 'पिकअपची पुष्टी करा',
      'confirm_delivery': 'डिलिव्हरीची पुष्टी करा',
    },
  };
}
